### ISSUE TITLE
Allow configuring the retention policy through a variable

### ISSUE THREAD

**Issue by sradevski** [balenablocks/dashboard#16]

**Comment by phil-d-wilson** [comment]
Hey - retention policy relates to InfluxDB, as the dashboard block (hence Grafana) will simply display any data it finds in the DB. It does not retain anything. We do not (at the time of writing) maintain an InfluxDB block, we use the official image in our projects such as balenaSense.

More about the influxDB retention policies can be found here:
https://www.influxdata.com/blog/influxdb-shards-retention-policies/
and here:
https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#retention-policy-management
